<a href="https://colab.research.google.com/github/nicolealf/Task_six/blob/main/python_project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

Question One

In [ ]:
print(A[4,2])

Question Two 

In [4]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
A[2]=[7,8,10]

In [7]:
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


The third row the matrix A was replaced by (7, 8, 10)

In [9]:
A[1]=[1,1,1]

In [10]:
print(A)


[[ 1  2  3]
 [ 1  1  1]
 [ 7  8 10]]


Question Three

The third line of code is replacing the second row of the matrix A by the sum of the second row and the first row multiplied by the negative of the second entry and the first column. The fourth line of code is replacing the third row of the matrix by the sum of the third row and the first row multiplied by the negative of the entry that is in the third row and the first column. The sixth line of code is replacing the third row of the matrix A by the sum of row three and row two which is then multiplied by the negative of the entry that is in the third row, second column and divided by the entry that is in the second row and second column. 

Question Four

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])

In [14]:
B = np.array([[-1], [4], [-10]])

In [15]:
print(B)

[[ -1]
 [  4]
 [-10]]


In [16]:
x = np.linalg.solve(A, B)


In [17]:
x

array([[-14.66666667],
       [ 35.33333333],
       [-19.        ]])

Question Five

In [18]:
np.matmul(A, x)

array([[ -1.],
       [  4.],
       [-10.]])

Question Six

In [22]:
from numpy.linalg import inv

In [23]:
Ainv = inv(A)

In [24]:
Ainv

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

In [26]:
np.matmul(Ainv, B)

array([[-14.66666667],
       [ 35.33333333],
       [-19.        ]])

Question Seven

Question Eight

In [27]:
from sympy.abc import a,b,c #allows us to use a,b,c in symbolic calculations

In [28]:
import sympy as sp

In [29]:
M=sp.Matrix([[1,2,3],[4,5,6],[7,8,9]]) 

In [31]:
print(M)

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [32]:
N=sp.Matrix([[a,0,0],[0,b,0],[0,0,c]])

In [33]:
print(N)

Matrix([[a, 0, 0], [0, b, 0], [0, 0, c]])


In [34]:
print(M*N)

Matrix([[a, 2*b, 3*c], [4*a, 5*b, 6*c], [7*a, 8*b, 9*c]])


In [35]:
print(M.rref())

(Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0]]), (0, 1))


In [38]:
N=sp.Matrix([[x+5, x-4, (x-2)**2, x**2, x, 1] for x in [1,2,3,4,5,6]])

In [39]:
print(N)

Matrix([[6, -3, 1, 1, 1, 1], [7, -2, 0, 4, 2, 1], [8, -1, 1, 9, 3, 1], [9, 0, 4, 16, 4, 1], [10, 1, 9, 25, 5, 1], [11, 2, 16, 36, 6, 1]])


In [40]:
print(N.rref())

(Matrix([
[1, 0, 0, 4/3, 4/9,  1/9],
[0, 1, 0, 8/3, 5/9, -1/9],
[0, 0, 1,   1,   0,    0],
[0, 0, 0,   0,   0,    0],
[0, 0, 0,   0,   0,    0],
[0, 0, 0,   0,   0,    0]]), (0, 1, 2))


Question Nine

In [41]:
M=sp.Matrix([[1, x, x**2, x**3, x**4, x**5] for x in [2,3,4,5,6,7]])

In [42]:
print(M)

Matrix([[1, 2, 4, 8, 16, 32], [1, 3, 9, 27, 81, 243], [1, 4, 16, 64, 256, 1024], [1, 5, 25, 125, 625, 3125], [1, 6, 36, 216, 1296, 7776], [1, 7, 49, 343, 2401, 16807]])


In [43]:
M.det()

34560